import {
  pgTable,
  bigint,
  bigserial,
  text,
  jsonb,
  numeric,
  integer,
  smallint,
  timestamp,
  index,
  uniqueIndex,
  customType,
  boolean,
} from 'drizzle-orm/pg-core';

// pgvector column — drizzle doesn't know the vector type natively, so we
// declare it as a custom column that prints as `vector(N)` in the DDL.
// Reads and writes go through the `sql` raw client; this declaration is
// here so generate-migrations produces the right ALTER TABLE statement.
const vector = (dims: number) =>
  customType<{ data: number[]; driverData: string; default: false }>({
    dataType() {
      return `vector(${dims})`;
    },
    toDriver(value: number[]) {
      return `[${value.join(',')}]`;
    },
  });

export interface AgentMetadata {
  name?: string;
  description?: string;
  image?: string;
  agent_type?: string;
  capabilities?: string[];
  version?: string;
  creator?: string;
  location?: string;
  [key: string]: unknown;
}

export const agents = pgTable(
  'agents',
  {
    agentId: bigint('agent_id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    ownerAddress: text('owner_address').notNull(),
    metadataUri: text('metadata_uri'),
    metadata: jsonb('metadata').$type<AgentMetadata | null>(),
    name: text('name'),
    agentType: text('agent_type'),
    capabilities: jsonb('capabilities').$type<string[] | null>(),
    // F2 (Phase 2): coarse-grained category assigned by the rule-based
    // classifier in web/scripts/classify-corpus.ts. One of:
    //   trading | validation | assistants | payments | research | content
    //   utility | services | identity | other
    // Nullable — only agents with enough metadata to classify are tagged.
    category: text('category'),
    // Phase B / Track 4: 384-dim embedding of name + description + capabilities,
    // generated by @xenova/transformers all-MiniLM-L6-v2. Powers semantic
    // search on /discover and the POST /v1/route machine endpoint.
    // Nullable — only agents with metadata text get embedded (~2K of 18K).
    embedding: vector(384)('embedding'),
    reputationScore: numeric('reputation_score', { precision: 10, scale: 2 }),
    feedbackCount: integer('feedback_count').default(0).notNull(),
    validationStatus: text('validation_status'),
    jobsCompleted: integer('jobs_completed').default(0).notNull(),
    usdcEarned: numeric('usdc_earned', { precision: 30, scale: 6 }).default('0').notNull(),
    registeredAtBlock: bigint('registered_at_block', { mode: 'bigint' }).notNull(),
    registeredTxHash: text('registered_tx_hash').notNull(),
    registeredAt: timestamp('registered_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    ownerIdx: index('idx_agents_owner').on(table.ownerAddress),
    reputationIdx: index('idx_agents_reputation').on(table.reputationScore),
    earnedIdx: index('idx_agents_earned').on(table.usdcEarned),
    blockIdx: index('idx_agents_block').on(table.registeredAtBlock),
    nameIdx: index('idx_agents_name').on(table.name),
    capabilitiesGin: index('idx_agents_capabilities_gin').using('gin', table.capabilities),
    metadataGin: index('idx_agents_metadata_gin').using('gin', table.metadata),
    categoryIdx: index('idx_agents_category').on(table.category),
  }),
);

export type Agent = typeof agents.$inferSelect;
export type NewAgent = typeof agents.$inferInsert;

export const feedbackEvents = pgTable(
  'feedback_events',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    agentId: bigint('agent_id', { mode: 'bigint' })
      .notNull()
      .references(() => agents.agentId, { onDelete: 'cascade' }),
    validatorAddress: text('validator_address').notNull(),
    score: numeric('score', { precision: 10, scale: 2 }).notNull(),
    scoreType: integer('score_type'),
    tag: text('tag'),
    feedbackHash: text('feedback_hash'),
    blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
    txHash: text('tx_hash').notNull().unique(),
    logIndex: integer('log_index').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    agentIdIdx: index('idx_feedback_agent').on(table.agentId),
    blockIdx: index('idx_feedback_block').on(table.blockNumber),
    validatorIdx: index('idx_feedback_validator').on(table.validatorAddress),
  }),
);

export type FeedbackEvent = typeof feedbackEvents.$inferSelect;

export const validations = pgTable(
  'validations',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    agentId: bigint('agent_id', { mode: 'bigint' })
      .notNull()
      .references(() => agents.agentId, { onDelete: 'cascade' }),
    validatorAddress: text('validator_address').notNull(),
    requestHash: text('request_hash').notNull().unique(),
    requestUri: text('request_uri'),
    tag: text('tag'),
    status: text('status').notNull(),
    responseCode: integer('response_code'),
    responseUri: text('response_uri'),
    responseHash: text('response_hash'),
    requestedAtBlock: bigint('requested_at_block', { mode: 'bigint' }).notNull(),
    respondedAtBlock: bigint('responded_at_block', { mode: 'bigint' }),
    requestTxHash: text('request_tx_hash').notNull(),
    responseTxHash: text('response_tx_hash'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    agentIdx: index('idx_validations_agent').on(table.agentId),
    statusIdx: index('idx_validations_status').on(table.status),
    validatorIdx: index('idx_validations_validator').on(table.validatorAddress),
  }),
);

export type Validation = typeof validations.$inferSelect;

export const jobs = pgTable(
  'jobs',
  {
    jobId: bigint('job_id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    clientAddress: text('client_address').notNull(),
    providerAddress: text('provider_address').notNull(),
    evaluatorAddress: text('evaluator_address'),
    budgetUsdc: numeric('budget_usdc', { precision: 30, scale: 6 }),
    budgetRaw: text('budget_raw'),
    description: text('description'),
    status: text('status').notNull(),
    deliverableHash: text('deliverable_hash'),
    completionReason: text('completion_reason'),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
    createdAtBlock: bigint('created_at_block', { mode: 'bigint' }).notNull(),
    createdTxHash: text('created_tx_hash').notNull(),
    completedAtBlock: bigint('completed_at_block', { mode: 'bigint' }),
    completedTxHash: text('completed_tx_hash'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    providerIdx: index('idx_jobs_provider').on(table.providerAddress),
    clientIdx: index('idx_jobs_client').on(table.clientAddress),
    statusIdx: index('idx_jobs_status').on(table.status),
    blockIdx: index('idx_jobs_block').on(table.createdAtBlock),
    budgetIdx: index('idx_jobs_budget').on(table.budgetUsdc),
  }),
);

export type Job = typeof jobs.$inferSelect;

export const jobEvents = pgTable(
  'job_events',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    jobId: bigint('job_id', { mode: 'bigint' })
      .notNull()
      .references(() => jobs.jobId, { onDelete: 'cascade' }),
    eventType: text('event_type').notNull(),
    actorAddress: text('actor_address').notNull(),
    blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
    txHash: text('tx_hash').notNull().unique(),
    logIndex: integer('log_index').notNull(),
    data: jsonb('data'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    jobIdx: index('idx_job_events_job').on(table.jobId),
    blockIdx: index('idx_job_events_block').on(table.blockNumber),
    typeIdx: index('idx_job_events_type').on(table.eventType),
  }),
);

export type JobEvent = typeof jobEvents.$inferSelect;

export const indexerState = pgTable('indexer_state', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const jobDrafts = pgTable(
  'job_drafts',
  {
    draftId: text('draft_id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    draftHash: text('draft_hash').notNull(),
    chainId: text('chain_id').notNull().default('arc'),
    poster: text('poster').notNull(),
    targetAgentId: text('target_agent_id').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    budgetUsdc: text('budget_usdc').notNull(),
    minTier: smallint('min_tier').notNull(),
    minConfidence: smallint('min_confidence').notNull(),
    deadline: timestamp('deadline', { withTimezone: true }).notNull(),
    onchainJobId: text('onchain_job_id'),
    // Caliber bond is opt-in per job. When false (default), /jobs/[id]
    // hides the bond panel entirely. When true, the panel renders and the
    // agent is expected to post a bond before accepting.
    bondRequired: boolean('bond_required').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    posterIdx: index('idx_job_drafts_poster').on(table.poster),
    draftHashIdx: index('idx_job_drafts_hash').on(table.draftHash),
  }),
);

export type JobDraft = typeof jobDrafts.$inferSelect;
export type NewJobDraft = typeof jobDrafts.$inferInsert;

// Wave 3 — Rating Trajectory.
// Daily snapshot per (agent, chain, view) so the trajectory chart on the agent
// detail page can render a tier-over-time line, the stats page can show the
// registry's tier-mix evolution, and W4 (validator calibration) + W5
// (downgrade alerts) have a history to diff against.
//
// The cron job (rating/scripts/snapshot-daily.ts) inserts one PIT row per
// rateable agent per day. TTC rows are produced only when ≥180 days of
// history exist (per methodology §3.3); on a young testnet that won't fire
// for months, but the schema and view enum are ready for it.
export const ratingSnapshots = pgTable(
  'rating_snapshots',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    agentId: bigint('agent_id', { mode: 'bigint' }).notNull(),
    computedAt: timestamp('computed_at', { withTimezone: true }).notNull(),
    tier: text('tier').notNull(),
    ppd30d: numeric('ppd_30d', { precision: 8, scale: 6 }),
    lgd: numeric('lgd', { precision: 8, scale: 6 }),
    eadUsdc: text('ead_usdc'),
    confidence: text('confidence').notNull(),
    // Bitmask of risk flags as of this snapshot. Bits (matches engine FLAG_BIT):
    //   0x01 CounterpartyConcentration · 0x02 ValidatorConcentration
    //   0x04 SybilPattern · 0x08 VolumeAnomaly · 0x10 Dormancy
    // Nullable for backwards compat with snapshots taken before flag tracking.
    flags: smallint('flags'),
    view: text('view').notNull(),
    methodologyVersion: text('methodology_version').notNull(),
    interactionCount: integer('interaction_count'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    agentDayIdx: index('idx_snapshots_agent_day').on(table.agentId, table.computedAt),
    computedAtIdx: index('idx_snapshots_computed_at').on(table.computedAt),
    chainAgentIdx: index('idx_snapshots_chain_agent').on(table.chainId, table.agentId),
  }),
);

export type RatingSnapshot = typeof ratingSnapshots.$inferSelect;
export type NewRatingSnapshot = typeof ratingSnapshots.$inferInsert;

// Track 3 (Phase 2 voyage): tier-transition feed. One row per snapshot-to-
// snapshot transition that is "interesting" — first rating issued, tier
// moved up or down, flags added/removed, agent crossed into Watch or
// Dormant. Populated by snapshot-daily.ts after the day's snapshot insert.
//
// Kept narrow & append-only so the Watchlist UI + RSS feed + JSON endpoint
// can each read one table with no joins. methodology_version is included so
// transitions are interpretable even across version bumps.
export const tierTransitions = pgTable(
  'tier_transitions',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    chainId: text('chain_id').notNull().default('arc'),
    agentId: bigint('agent_id', { mode: 'bigint' }).notNull(),
    at: timestamp('at', { withTimezone: true }).notNull(),
    // Discrete change kind. Multiple transitions per day are allowed (e.g.
    // tier_down + flag_added on the same snapshot diff). Values:
    //   first_rating · tier_up · tier_down · flag_added · flag_removed
    //   enter_watch · enter_dormant · exit_watch · exit_dormant
    kind: text('kind').notNull(),
    fromTier: text('from_tier'),
    toTier: text('to_tier').notNull(),
    fromFlags: smallint('from_flags'),
    toFlags: smallint('to_flags').notNull(),
    fromScore: smallint('from_score'),
    toScore: smallint('to_score'),
    methodologyVersion: text('methodology_version').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    atIdx: index('idx_transitions_at').on(table.at),
    agentIdx: index('idx_transitions_agent').on(table.agentId, table.at),
    kindIdx: index('idx_transitions_kind').on(table.kind, table.at),
  }),
);

export type TierTransition = typeof tierTransitions.$inferSelect;
export type NewTierTransition = typeof tierTransitions.$inferInsert;

// Phase B polish: Discord webhook subscriptions for the Watchlist feed.
// Anyone can paste a Discord webhook URL + filter mask; the daily snapshot
// fans new tier_transitions out to each active subscription. No email
// confirmation flow — the URL itself is the secret. Auto-pauses a webhook
// after consecutive_failures >= 3 so a dead/private channel can't burn
// our delivery budget forever.
export const watchlistWebhooks = pgTable(
  'watchlist_webhooks',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    webhookUrl: text('webhook_url').notNull().unique(),
    // Comma-separated transition kinds, or '*' for all. e.g. 'tier_down,enter_watch,flag_added'
    kindFilter: text('kind_filter').notNull().default('*'),
    status: text('status').notNull().default('active'), // 'active' | 'paused'
    consecutiveFailures: integer('consecutive_failures').notNull().default(0),
    lastFiredAt: timestamp('last_fired_at', { withTimezone: true }),
    lastErrorAt: timestamp('last_error_at', { withTimezone: true }),
    lastError: text('last_error'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    statusIdx: index('idx_webhooks_status').on(table.status),
  }),
);

export type WatchlistWebhook = typeof watchlistWebhooks.$inferSelect;
export type NewWatchlistWebhook = typeof watchlistWebhooks.$inferInsert;

// D2: judge-demo funded wallet tracking. When a user creates a Circle wallet
// via Google or Email OTP, the server drips a small amount of test USDC from
// the TEST_FUNDER wallet so judges can walk the full gated-job demo without
// hitting Circle's faucet. Primary-keyed on address for idempotency — repeat
// calls return the original txHash instead of double-funding.
export const fundedWallets = pgTable('funded_wallets', {
  address: text('address').primaryKey(),
  txHash: text('tx_hash').notNull(),
  amountUsdc: text('amount_usdc').notNull(),
  fundedAt: timestamp('funded_at', { withTimezone: true }).defaultNow().notNull(),
});

export type FundedWallet = typeof fundedWallets.$inferSelect;

// Lepton Phase 1 (A2): payments ledger for the metered x402 attestation API.
// One row per request that passes through x402Middleware — paid OR bypassed.
//
// Honest traction (Guardrail 4): every row carries a `payer_class`, resolved at
// insert time from packages/db/src/known-wallets.ts. Public metrics are always
// reportable split by class; we never present self-generated volume as external
// users. Bypass-token requests are recorded `internal`, amount 0 — they are not
// payments and never count as revenue.
//
// `payment_ref` (the Gateway settle/batch reference) is UNIQUE so a replayed
// payment is rejected at our layer even if the facilitator would also catch it.
// Bypass/internal rows have no real reference; they use a synthetic
// `internal:<uuid>` value so the UNIQUE constraint still holds.
export const meteredPayments = pgTable(
  'metered_payments',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    payerAddress: text('payer_address').notNull(),
    // 'external' | 'demo' | 'internal' — see PAYER_CLASSES in known-wallets.ts.
    payerClass: text('payer_class').notNull(),
    endpoint: text('endpoint').notNull(),
    agentId: bigint('agent_id', { mode: 'bigint' }),
    amountUsdc: numeric('amount_usdc', { precision: 18, scale: 6 }).notNull(),
    // Gateway settle/batch reference — unique key for replay protection.
    paymentRef: text('payment_ref').notNull().unique(),
    latencyMs: integer('latency_ms'),
    // 'settled' (default) | 'bypass' | 'refund_pending' | 'failed'
    status: text('status').notNull().default('settled'),
  },
  (table) => ({
    createdAtIdx: index('idx_metered_payments_created_at').on(table.createdAt),
    payerIdx: index('idx_metered_payments_payer').on(table.payerAddress),
    classIdx: index('idx_metered_payments_class').on(table.payerClass),
  }),
);

export type MeteredPayment = typeof meteredPayments.$inferSelect;
export type NewMeteredPayment = typeof meteredPayments.$inferInsert;

// Lepton Phase 1 (A1.4): refund queue. If the facilitator settles a payment but
// the downstream attestation signing then fails, we must NOT silently keep the
// funds. The middleware enqueues a row here for manual handling instead.
export const meteredRefundQueue = pgTable('metered_refund_queue', {
  id: bigserial('id', { mode: 'bigint' }).primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  payerAddress: text('payer_address').notNull(),
  amountUsdc: numeric('amount_usdc', { precision: 18, scale: 6 }).notNull(),
  paymentRef: text('payment_ref').notNull(),
  reason: text('reason').notNull(),
  resolved: boolean('resolved').notNull().default(false),
});

export type MeteredRefund = typeof meteredRefundQueue.$inferSelect;

// Lepton Phase 1 (A4): HireBot decision log. HireBot is a budget-aware agent
// that decides, per funded job, whether paying the metered price for a trust
// check is worth it — then applies a hire rule. Every decision is persisted so
// the dashboard can render the agent's reasoning verbatim (the human-readable
// `rationale` is the agentic-sophistication evidence). The table is also the
// agent's state: daily spend = sum(cost_usdc) for today; the cache is "is there
// a recent `purchased` row for this provider".
//
// `tier`/`score` extend the plan's shape sketch so a cache_hit can reuse the
// last attestation result without re-paying, and the dashboard can show it.
export const hirebotDecisions = pgTable(
  'hirebot_decisions',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    jobId: bigint('job_id', { mode: 'bigint' }),
    providerId: bigint('provider_id', { mode: 'bigint' }),
    // purchased | cache_hit | not_worth_it | budget_blocked | would_hire | would_skip
    action: text('action').notNull(),
    rationale: text('rationale').notNull(),
    costUsdc: numeric('cost_usdc', { precision: 18, scale: 6 }).notNull().default('0'),
    budgetLeft: numeric('budget_left', { precision: 18, scale: 6 }).notNull(),
    // Attestation result captured when known (null for skips/unrated providers).
    tier: text('tier'),
    score: smallint('score'),
    // Settle reference of the nanopayment, when this decision paid.
    paymentRef: text('payment_ref'),
  },
  (table) => ({
    createdAtIdx: index('idx_hirebot_created_at').on(table.createdAt),
    providerIdx: index('idx_hirebot_provider').on(table.providerId),
    actionIdx: index('idx_hirebot_action').on(table.action),
  }),
);

export type HirebotDecision = typeof hirebotDecisions.$inferSelect;
export type NewHirebotDecision = typeof hirebotDecisions.$inferInsert;

// Lepton Phase 2 (B2): Bonded Broker match log. The Broker is a reference
// *consumer* of Caliber (neutrality — it does not issue ratings). Each match
// request records the full reasoning: candidates queried, attestations bought
// (multi-hop x402), the decline/accept verdict, the fee charged, and the bond
// posted. `decision_log` is the ordered rationale stream the console renders.
export const brokerMatches = pgTable(
  'broker_matches',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    requesterAddr: text('requester_addr').notNull(),
    jobId: bigint('job_id', { mode: 'bigint' }),
    providerId: bigint('provider_id', { mode: 'bigint' }),
    // evaluating | declined | matched | bonded | released | slashed
    status: text('status').notNull(),
    feeUsdc: numeric('fee_usdc', { precision: 18, scale: 6 }),
    bondUsdc: numeric('bond_usdc', { precision: 18, scale: 6 }),
    bondId: bigint('bond_id', { mode: 'bigint' }),
    attestationsBought: integer('attestations_bought').notNull().default(0),
    declineReason: text('decline_reason'),
    // Ordered rationale steps: [{ step, detail, ref? }]
    decisionLog: jsonb('decision_log').$type<unknown[]>().notNull().default([]),
  },
  (table) => ({
    createdAtIdx: index('idx_broker_matches_created_at').on(table.createdAt),
    statusIdx: index('idx_broker_matches_status').on(table.status),
  }),
);

export type BrokerMatch = typeof brokerMatches.$inferSelect;
export type NewBrokerMatch = typeof brokerMatches.$inferInsert;

// ---------------------------------------------------------------------------
// Steward (autonomous payment governor) — STEWARD_PLAN.md §3.
// Steward is a proxy service (:3300) that probes, authorizes, signs, pays and
// ledgers x402 payments on behalf of agents. The tables below back the
// pipeline ledger, the mandate compiler, the incident/approval surfaces, the
// route-pause state, the counterparty cache, and the integration-key counter.
// ---------------------------------------------------------------------------

// A mandate is the natural-language spending policy authored in the console.
// `raw_text` is what the operator wrote; `compiled_policy` is the LLM-compiled
// machine policy the pipeline actually enforces. Versioned + append-only: a new
// edit inserts a fresh row (version+1, status 'active') and supersedes the prior.
export const stewardMandates = pgTable('steward_mandates', {
  id: bigserial('id', { mode: 'bigint' }).primaryKey(),
  rawText: text('raw_text').notNull(),
  compiledPolicy: jsonb('compiled_policy').notNull(),
  compileModel: text('compile_model'),
  version: integer('version').notNull().default(1),
  // 'active' | 'superseded'
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export type StewardMandate = typeof stewardMandates.$inferSelect;
export type NewStewardMandate = typeof stewardMandates.$inferInsert;

// Steward Phase 2 (WS-1): the signed DeliverySpec. Buyer (and optionally seller)
// sign an EIP-712 DeliverySpec BEFORE payment — a pre-agreed, provable contract
// for what the seller must deliver (URL, schema, size/deadline budget, JSON/
// ok-field requirements). Tier-0 conformance bounds are then derived FROM this
// spec instead of from response-observed defaults, making a breach attributable
// + disputable. `spec_hash` (the EIP-712 typed-data hash) is the dedupe key and
// the stable handle later embedded in an EvidenceAttestation (WS-2).
//
// `seller_sig` is nullable: a buyer-only-signed spec is accepted-but-undisputable
// (no seller counter-signature to point at on a dispute). `raw_spec` stores the
// exact typed message (bigint fields as strings) so the spec hash + signatures
// can be re-verified verbatim.
export const stewardSpecs = pgTable(
  'steward_specs',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    specHash: text('spec_hash').notNull().unique(),
    chain: text('chain').notNull().default('arc'),
    buyer: text('buyer').notNull(),
    seller: text('seller').notNull(),
    sellerUrlHash: text('seller_url_hash'),
    schemaHash: text('schema_hash'),
    maxBytes: integer('max_bytes'),
    deadlineMs: integer('deadline_ms'),
    requireJson: boolean('require_json'),
    requireOkField: boolean('require_ok_field'),
    validUntil: timestamp('valid_until', { withTimezone: true }),
    nonce: numeric('nonce'),
    buyerSig: text('buyer_sig').notNull(),
    // Null = buyer-only-signed (accepted, but undisputable — no seller commitment).
    sellerSig: text('seller_sig'),
    rawSpec: jsonb('raw_spec').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    buyerIdx: index('idx_steward_specs_buyer').on(table.buyer),
    sellerIdx: index('idx_steward_specs_seller').on(table.seller),
  }),
);

export type StewardSpec = typeof stewardSpecs.$inferSelect;
export type NewStewardSpec = typeof stewardSpecs.$inferInsert;

// The ledger. One row per payment intent that passes through the pipeline —
// allowed, held, or denied. `decision_stage` records where in the pipeline the
// verdict was reached. `incident_id` is a PLAIN bigint (no FK) on purpose: it
// would otherwise form a circular FK with steward_incidents.payment_id.
export const stewardPayments = pgTable(
  'steward_payments',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    requestId: text('request_id').notNull().unique(),
    // 'hirebot' | 'api' | integration key name
    source: text('source').notNull(),
    sellerUrl: text('seller_url').notNull(),
    host: text('host').notNull(),
    payTo: text('pay_to'),
    quotedUsdc: numeric('quoted_usdc', { precision: 18, scale: 6 }),
    settledUsdc: numeric('settled_usdc', { precision: 18, scale: 6 }),
    // 'allow' | 'hold' | 'deny'
    decision: text('decision').notNull(),
    // 'frozen' | 'policy' | 'detector' | 'sdn' | 'treasurer' | 'approval' | 'executed'
    decisionStage: text('decision_stage').notNull(),
    reasoning: text('reasoning'),
    detectorHits: jsonb('detector_hits'),
    // The original request ({ url, init, source }) captured on a HELD payment so
    // it can be re-executed verbatim through the pipeline when the hold is approved.
    requestInit: jsonb('request_init'),
    sdnSource: text('sdn_source'),
    sdnCheckedAt: timestamp('sdn_checked_at', { withTimezone: true }),
    sdnResult: jsonb('sdn_result'),
    caliberScore: smallint('caliber_score'),
    llmModel: text('llm_model'),
    paymentRef: text('payment_ref').unique(),
    // 'n/a' | 'settled' | 'failed' | 'mismatch'
    settleStatus: text('settle_status'),
    mandateId: bigint('mandate_id', { mode: 'bigint' }).references(() => stewardMandates.id),
    // PLAIN column, NO foreign key — avoids a circular FK with steward_incidents.
    incidentId: bigint('incident_id', { mode: 'bigint' }),
    // WS-1: the signed DeliverySpec this payment was governed by (null = the
    // legacy unsigned-`expect` path, Tier-0-only and non-disputable).
    specId: bigint('spec_id', { mode: 'bigint' }).references(() => stewardSpecs.id),
    // WS-1: which verification tier resolved conformance. 0 = Tier-0
    // deterministic checks (the only tier today). Set when a signed spec governs.
    verificationTier: smallint('verification_tier'),
    latencyMs: integer('latency_ms'),
  },
  (table) => ({
    createdAtIdx: index('idx_steward_payments_created_at').on(table.createdAt),
    hostIdx: index('idx_steward_payments_host').on(table.host),
    decisionIdx: index('idx_steward_payments_decision').on(table.decision),
  }),
);

export type StewardPayment = typeof stewardPayments.$inferSelect;
export type NewStewardPayment = typeof stewardPayments.$inferInsert;

// Detector / SDN / settle anomalies surface here as incidents, with an
// LLM-authored `narrative`. `payment_id` links back to the offending ledger row.
export const stewardIncidents = pgTable(
  'steward_incidents',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    // 'runaway_loop' | 'price_spike' | 'redirect' | 'new_counterparty'
    //   | 'conformance' | 'sdn_hit' | 'settle_mismatch'
    kind: text('kind').notNull(),
    severity: text('severity').notNull().default('medium'),
    // 'open' | 'resolved'
    status: text('status').notNull().default('open'),
    host: text('host'),
    payTo: text('pay_to'),
    paymentId: bigint('payment_id', { mode: 'bigint' }).references(() => stewardPayments.id),
    evidence: jsonb('evidence'),
    narrative: text('narrative'),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    resolvedBy: text('resolved_by'),
  },
  (table) => ({
    createdAtIdx: index('idx_steward_incidents_created_at').on(table.createdAt),
    statusIdx: index('idx_steward_incidents_status').on(table.status),
  }),
);

export type StewardIncident = typeof stewardIncidents.$inferSelect;
export type NewStewardIncident = typeof stewardIncidents.$inferInsert;

// Pending human approvals for held payments. Pushed to Telegram (inline
// approve/deny buttons) with an expiry; also approvable from the web console.
export const stewardApprovals = pgTable('steward_approvals', {
  id: bigserial('id', { mode: 'bigint' }).primaryKey(),
  paymentId: bigint('payment_id', { mode: 'bigint' })
    .notNull()
    .references(() => stewardPayments.id),
  incidentId: bigint('incident_id', { mode: 'bigint' }).references(() => stewardIncidents.id),
  // 'pending' | 'approved' | 'denied' | 'expired'
  status: text('status').notNull().default('pending'),
  telegramChatId: text('telegram_chat_id'),
  telegramMessageId: text('telegram_message_id'),
  requestedAt: timestamp('requested_at', { withTimezone: true }).defaultNow().notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  // 'telegram' | 'web'
  decidedVia: text('decided_via'),
});

export type StewardApproval = typeof stewardApprovals.$inferSelect;
export type NewStewardApproval = typeof stewardApprovals.$inferInsert;

// Per-(host, path_prefix) circuit breaker. A route can be paused (manually or
// by a detector) and optionally auto-resumed.
export const stewardRoutes = pgTable(
  'steward_routes',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    host: text('host').notNull(),
    pathPrefix: text('path_prefix').notNull().default(''),
    // 'active' | 'paused'
    status: text('status').notNull().default('active'),
    pausedReason: text('paused_reason'),
    pausedAt: timestamp('paused_at', { withTimezone: true }),
    autoResumeAt: timestamp('auto_resume_at', { withTimezone: true }),
  },
  (table) => ({
    hostPathUnique: uniqueIndex('uq_steward_routes_host_path').on(table.host, table.pathPrefix),
  }),
);

export type StewardRoute = typeof stewardRoutes.$inferSelect;
export type NewStewardRoute = typeof stewardRoutes.$inferInsert;

// Known counterparty cache keyed on payTo. Holds registration/trust flags, an
// SDN-check cache, and trailing payment stats (count, total, price median) used
// by the price-spike + new-counterparty detectors.
export const stewardCounterparties = pgTable('steward_counterparties', {
  id: bigserial('id', { mode: 'bigint' }).primaryKey(),
  payTo: text('pay_to').notNull().unique(),
  host: text('host'),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
  registered: boolean('registered').notNull().default(false),
  trusted: boolean('trusted').notNull().default(false),
  sdnResult: jsonb('sdn_result'),
  sdnCheckedAt: timestamp('sdn_checked_at', { withTimezone: true }),
  paymentCount: integer('payment_count').notNull().default(0),
  totalUsdc: numeric('total_usdc', { precision: 18, scale: 6 }).notNull().default('0'),
  priceMedianUsdc: numeric('price_median_usdc', { precision: 18, scale: 6 }),
});

export type StewardCounterparty = typeof stewardCounterparties.$inferSelect;
export type NewStewardCounterparty = typeof stewardCounterparties.$inferInsert;

// Singleton-ish key/value state for the service (e.g. the `frozen` flag).
export const stewardState = pgTable('steward_state', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export type StewardState = typeof stewardState.$inferSelect;
export type NewStewardState = typeof stewardState.$inferInsert;

// Integration API keys → "teams integrated" counter. `api_key_hash` is the
// stored hash (never the raw key); `payer_class` tags ledger rows for honest
// external/demo/internal traction reporting.
export const stewardIntegrations = pgTable('steward_integrations', {
  id: bigserial('id', { mode: 'bigint' }).primaryKey(),
  name: text('name').notNull().unique(),
  apiKeyHash: text('api_key_hash').notNull(),
  payerClass: text('payer_class').notNull().default('external'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
});

export type StewardIntegration = typeof stewardIntegrations.$inferSelect;
export type NewStewardIntegration = typeof stewardIntegrations.$inferInsert;

// Steward Phase 2 (WS-2 + WS-3): the flagship evidence record. When a signed-spec
// payment breaches its pre-agreed DeliverySpec, Steward signs an EIP-712
// EvidenceAttestation (the rating signer key) and records it on-chain in the
// EvidenceRegistry. The on-chain event is the canonical record; this table is the
// off-chain index + the bridge into the Caliber rating engine.
//
// `verdict`        0 = conforms · 1 = breach · 2 = inconclusive (steward-core VERDICT).
// `verifying_tier` 0..3 — the judge Tier that resolved the verdict (0 today).
// `onchain_tx`     the attest() tx hash; NULL when the chain send failed (the row is
//                  still written so it can be retried — `attestation`/`signature`
//                  hold the verbatim signed envelope to re-broadcast).
// `feedback_event_id` — for a BREACH, the synthetic validator-observation row this
//                  evidence wrote into feedback_events (score 0, tag steward:breach).
//                  That row is what flows through rateAgent() and drops the score.
export const stewardEvidence = pgTable(
  'steward_evidence',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    paymentId: bigint('payment_id', { mode: 'bigint' }).references(() => stewardPayments.id),
    specHash: text('spec_hash'),
    responseHash: text('response_hash'),
    agentId: bigint('agent_id', { mode: 'bigint' }),
    verdict: smallint('verdict'),
    verifyingTier: smallint('verifying_tier'),
    buyerSig: text('buyer_sig'),
    sellerSig: text('seller_sig'),
    methodologyVersion: text('methodology_version'),
    // The verbatim signed EvidenceAttestation message (bigint fields as strings) so
    // a failed on-chain send can be re-broadcast without re-signing.
    attestation: jsonb('attestation'),
    signature: text('signature'),
    onchainTx: text('onchain_tx'),
    feedbackEventId: bigint('feedback_event_id', { mode: 'bigint' }),
    // Steward Phase 2 (WS-4): the Tier-1 LLM judge's structured verdict
    // ({ conforms, violations:[{field,reason}], confidence }). Persisted on the
    // evidence row so a Tier-1 breach attestation carries its adjudication, and a
    // Tier-1 result that CORROBORATES an existing Tier-0 breach is recorded here
    // (no double attestation). NULL on a pure Tier-0 evidence row.
    judgeVerdict: jsonb('judge_verdict'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    paymentIdx: index('idx_steward_evidence_payment').on(table.paymentId),
    agentIdx: index('idx_steward_evidence_agent').on(table.agentId),
    createdAtIdx: index('idx_steward_evidence_created_at').on(table.createdAt),
  }),
);

export type StewardEvidence = typeof stewardEvidence.$inferSelect;
export type NewStewardEvidence = typeof stewardEvidence.$inferInsert;
