/var/log/arc-indexer.log
/var/log/arc-indexer-err.log
/var/log/arc-web.log
/var/log/arc-web-err.log
{
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0644 huicom huicom
    postrotate
        systemctl reload arc-indexer-live arc-web > /dev/null 2>&1 || true
    endscript
}
